server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: payment_route                       # 路由唯一ID
#          uri: http://localhost:8001              # 路由匹配的路径
          uri: lb://CLOUD-PAYMENT-SERVICE         #匹配后提供服务的路由地址
          predicates:                             # 断言 -> 路由匹配规则
            - Path=/payment/getPaymentById/**     # 断言路径为true放行

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE         #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
            - After=2022-02-15T17:10:03.685+08:00[Asia/Shanghai]  # 断言，在指定时间之后才能访问
#            # 断言，在指定时间范围内才能访问
#            - Between=2022-02-02T17:45:06.206+08:00[Asia/Shanghai],2023-03-25T18:59:06.206+08:00[Asia/Shanghai]
#            - Cookie=username,xiaozhi     # cookie中username=小智才能访问
#            - Method=GET  # 请求方法是GET
#            - Query=name
#            - Host=localhost
          filters:
            - AddRequestHeader=X-Request-Id,xiaozhi666  # 过滤器会在匹配的请求头上加一对请求头，名为X-Request-Id，值为444

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

