server:
  port: 2003

spring:
  application:
    name: seata-account-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: fsp-tx-group

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.10:3306/seata_account
    username: root
    password: abc123

feign:
  hystrix:
    enabled: false


logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xiaozhi.springcloud.domain
  configuration:
    map-underscore-to-camel-case: true
