server:
  port: 2002

spring:
  application:
    name: seata-storage-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: fsp-tx-group

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.10:3306/seata_storage
    username: root
    password: abc123

feign:
  hystrix:
    enabled: false

##################### seata配置 ######################
seata:
  tx-service-group: fsp_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xiaozhi.springcloud.domain
  configuration:
    map-underscore-to-camel-case: true
