server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider   # 应用名

  rabbitmq:
    host: 192.168.6.156
    port: 5672
    username: guest
    password: guest

  cloud:
    ####################### stream配置 ########################
    stream:
      binders:  # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
#          environment: # 设置rabbitmq的相关的环境配置

      bindings: # 服务的整合处理
        output:  # 这个名字是一个通道的名称
          destination: studyExchange      # 表示要使用的Exchange名称定义
          content-type: application/json  # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit           # 设置要绑定的消息服务的具体设置

  ####################### rabbitmq配置 ########################


####################### eureka配置 ########################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: send-8801.com    # 在信息列表时显示主机名称
    prefer-ip-address: true       # 访问的路径变为IP地址





