server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mazhi-oss/spring-cloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - spring-cloud-config
        # 由于github 2020-10-1 将主分支修改为main,所以要修改默认的label
        defaultLabel: main
      ####读取分支
      label: main

  # rabbitmq配置
  rabbitmq:
    host: 192.168.6.156
    port: 5672
    username: guest
    password: guest


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

